{{- if .Values.sentry.ingestConsumer.autoscaling.enabled }}
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "sentry.fullname" . }}-sentry-billing-metrics-consumer
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ template "sentry.fullname" . }}-billing-metrics-consumer
  minReplicas: {{ .Values.sentry.ingestConsumer.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.sentry.ingestConsumer.autoscaling.maxReplicas }}
  targetCPUUtilizationPercentage: {{ .Values.sentry.ingestConsumer.autoscaling.targetCPUUtilizationPercentage }}
{{- end }}
